heat_template_version: 2014-10-16

description: >
  Add sdb to volume group, remove loopback device

parameters:
  servers:
    type: json
  input_values:
    type: json

resources:
  CinderVolumeConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config: {get_file: /home/stack/templates/firstboot/cinder-volume-config.sh}

  CinderVolumeDeployment:
    type: OS::Heat::SoftwareDeployments
    properties:
      name: CinderVolumeDeployment
      servers: {get_param: [servers,BlockStorage]}
      config:  {get_resource: CinderVolumeConfig}
      actions: ['CREATE','UPDATE'] # do this on CREATE and UPDATE
      input_values: {get_param: input_values}
